### ISSUE TITLE
python-libcombine source archive is invalid

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/libCombine#60]
When installing python-libcombine for Python 3.11 on MacOS 10.15 (and only that combination!) various python libraries don't exist for some packages, so pip starts trying to find older versions that will work instead.  It then runs into a problem with the VERSION.txt file not existing in the previous version of python-libcombine 0.2.18:

```
2023-02-09T05:32:01.4358400Z Collecting python-libcombine
2023-02-09T05:32:01.4472120Z   Downloading python-libcombine-0.2.18.tar.gz (6.8 kB)
2023-02-09T05:32:01.4610110Z   Preparing metadata (setup.py): started
2023-02-09T05:32:01.7050130Z   Preparing metadata (setup.py): finished with status 'error'
2023-02-09T05:32:01.7148450Z   error: subprocess-exited-with-error
2023-02-09T05:32:01.7150230Z   
2023-02-09T05:32:01.7152540Z   × python setup.py egg_info did not run successfully.
2023-02-09T05:32:01.7157010Z   │ exit code: 1
2023-02-09T05:32:01.7158670Z   ╰─> [9 lines of output]
2023-02-09T05:32:01.7159800Z       Traceback (most recent call last):
2023-02-09T05:32:01.7161160Z         File "<string>", line 2, in <module>
2023-02-09T05:32:01.7163340Z         File "<pip-setuptools-caller>", line 34, in <module>
2023-02-09T05:32:01.7166250Z         File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-3w1dlj1t/python-libcombine_013133fc087f4099bfa721dd3532f8ca/setup.py", line 97, in <module>
2023-02-09T05:32:01.7170010Z           raise ValueError("Invalid libCombine Source directory, no VERSION.txt file")
2023-02-09T05:32:01.7173110Z       ValueError: Invalid libCombine Source directory, no VERSION.txt file
2023-02-09T05:32:01.7179900Z       Using libCombine from: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-3w1dlj1t/python-libcombine_013133fc087f4099bfa721dd3532f8ca
2023-02-09T05:32:01.7184900Z       Using VERSION.txt: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-3w1dlj1t/python-libcombine_013133fc087f4099bfa721dd3532f8ca/VERSION.txt
2023-02-09T05:32:01.7186690Z       ['PKG-INFO', 'LICENSE.md', 'python_libcombine.egg-info', 'README.md', 'setup.py', 'setup.cfg']
2023-02-09T05:32:01.7187440Z       [end of output]
2023-02-09T05:32:01.7188660Z   
2023-02-09T05:32:01.7189330Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2023-02-09T05:32:01.7190360Z error: metadata-generation-failed
2023-02-09T05:32:01.7190680Z 
2023-02-09T05:32:01.7191550Z × Encountered error while generating package metadata.
2023-02-09T05:32:01.7192660Z ╰─> See above for output.
2023-02-09T05:32:01.7193010Z 
2023-02-09T05:32:01.7194130Z note: This is an issue with the package mentioned above, not pip.
2023-02-09T05:32:01.7194980Z hint: See above for details.
```

The simplest solution might be to just yank that old version, and let pip deal with the fallout however it can?  I assume that the most recent version has a VERSION.txt?

At any rate, a somewhat obscure bug, but hopefully a straightforward solution.

**Comment by fbergmann** [comment]
yus i should definitely delete the source package that does not work. Uhm .. but do you really need bindings for catalina still?

**Comment by luciansmith** [comment]
This is for our own released binaries, so I plan to use Catalina until they pry it from my automatic build system ;-)

(libcombine is only being used for testing, but it'd be nice to be able to test it.)

**Comment by fbergmann** [comment]
for the binaries that you control, i think you'll have to do 10.13 (high sierra) that is what would run on my mac here, and up until the new releases .. then big sur for both intel and arm. 

as far as this repo is concerned, i'm afraid the source package just does not work at all, and i'll have to find a way to generate one that does. including all the submodules and stuff.

**Comment by luciansmith** [comment]
Oh, in that case, don't worry about it.  Everything works fine for all other combinations; I'll just tell it to not run the tests for that one particular combination.  Thank you, though!

**Comment by fbergmann** [comment]
ok, I think I've solved the issue. This [source archive](https://github.com/sbmlteam/libCombine/suites/11381204161/artifacts/585664341) compiles for me fine
